### ISSUE TITLE
Event study implementation

### ISSUE THREAD

**Issue by apoorvalal** [py-econometrics/duckreg#2]
Possibly beg @grantmcdermott to contribute a version of `etwfe` ? :smile:

**Comment by grantmcdermott** [comment]
Oof. Stretched very thin ATM but will look into it when I can.

This looks like rad btw. I half a mind to implement something like this a while ago, but never put digital pen to paper.

See also: https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/udfs/community/README.md

**Comment by apoorvalal** [comment]
Just merged a PR that implements the dynamic specifications of Two-way Mundlak. Demo here; would appreciate you taking a pass, grant. 
https://github.com/py-econometrics/duckreg/blob/master/notebooks/event_study.ipynb

**Comment by grantmcdermott** [comment]
Nice!

Still slammed but will take a look when I can.
